name: flash_reporter
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.15.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.6.0
  firebase_auth: ^4.11.1
  image_picker: ^0.8.7
  path_provider: ^2.1.1
  pdf: ^3.10.0
  provider: ^6.0.5
  flutter_quill: ^10.8.5
  intl: ^0.19.0
  printing: ^5.11.0
  firebase_crashlytics: ^3.0.18
  equatable: ^2.0.5
 # quill_delta: ^3.0.0-nullsafety.2
  docx_template: ^0.4.0
  file_picker: ^6.1.2

  #quill_delta: ^3.0.0
#dependency_overrides:
  #quill_delta: ^3.0.0-nullsafety.2
  

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/templates/