// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGVwFdGT-O3swfMs3keP9wUf8GqbtUrBg',
    appId: '1:936915784399:web:470b4c0e03d3bc78ed1dba',
    messagingSenderId: '936915784399',
    projectId: 'flashreporter-fae91',
    authDomain: 'flashreporter-fae91.firebaseapp.com',
    storageBucket: 'flashreporter-fae91.firebasestorage.app',
    measurementId: 'G-JG8KDN89LC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9xnTB4PyxUn2524p-yJ9GbkLl-Aszirc',
    appId: '1:936915784399:android:dfa9430ff511b15fed1dba',
    messagingSenderId: '936915784399',
    projectId: 'flashreporter-fae91',
    storageBucket: 'flashreporter-fae91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9cZx_0ay-rMqTODMwdaZhMLqsKKMqxKc',
    appId: '1:936915784399:ios:df01bd454d2c4ccfed1dba',
    messagingSenderId: '936915784399',
    projectId: 'flashreporter-fae91',
    storageBucket: 'flashreporter-fae91.firebasestorage.app',
    iosBundleId: 'com.example.repoter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9cZx_0ay-rMqTODMwdaZhMLqsKKMqxKc',
    appId: '1:936915784399:ios:df01bd454d2c4ccfed1dba',
    messagingSenderId: '936915784399',
    projectId: 'flashreporter-fae91',
    storageBucket: 'flashreporter-fae91.firebasestorage.app',
    iosBundleId: 'com.example.repoter1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGVwFdGT-O3swfMs3keP9wUf8GqbtUrBg',
    appId: '1:936915784399:web:4cdb845176a7ae7fed1dba',
    messagingSenderId: '936915784399',
    projectId: 'flashreporter-fae91',
    authDomain: 'flashreporter-fae91.firebaseapp.com',
    storageBucket: 'flashreporter-fae91.firebasestorage.app',
    measurementId: 'G-K8SLZCFDL1',
  );

}